name: models
description: 弗田使用的model

environment:
    sdk: '>=2.17.0 <3.0.0'

dependencies:
    json_annotation: ^4.8.1
    tools:
        git:
            url: https://github.com/LucidQuantum/tools.git
            ref: main

dev_dependencies:
    lints: ^2.0.0
    test: ^1.16.0
    json_serializable: ^6.6.2
    build_runner: ^2.2.2
