name: models
description: 弗田使用的model（前后端共用）

environment:
    sdk: '>=3.0.0 <4.0.0'

dependencies:
    mongo_dart: ^0.9.1
    jaguar_jwt: ^3.0.0
    json_annotation: ^4.8.1
    tools:
        git:
            url: https://github.com/LucidQuantum/tools.git
            ref: main

dev_dependencies:
    lints: ^2.1.0
    test: ^1.24.2
    json_serializable: ^6.6.2
    build_runner: ^2.4.4
