name: models
description: 弗田使用的model

environment:
    sdk: '>=2.17.0 <3.0.0'

dependencies:
    tools:
        git:
            url: https://github.com/LucidQuantum/tools.git
            ref: main

dev_dependencies:
    lints: ^2.0.0
    test: ^1.16.0
